# general
default_account: ukaea-ap001-gpu
default_qos: <QOS>

# working/log directories
chdir: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/UPT/UPT
output: /home/ir-zani1/rds/rds-ukaea-ap001/ir-zani1/UPT/UPT/%j.out

# environment setup
master_port: 55555
env_name: <ENV_NAME>

# LD_LIBRARY_PATH
ld_lib_path: <USER_DIR>/.conda/envs/<ENV_NAME>/lib
